# Generated by Django 3.2.5 on 2021-07-31 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_account_is_email_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='age',
            field=models.CharField(choices=[(-4, '16-20'), (-4, '20-24'), (-6, '24-30'), (-10, '30-40'), (-10, '40-50'), (-10, '50-60'), (60, '60+')], max_length=30),
        ),
    ]
