# Generated by Django 3.2.5 on 2021-07-31 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_account_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='is_staff',
            field=models.BooleanField(choices=[(0, 'Draft'), (1, 'Publish')], default=False),
        ),
    ]
