# Generated by Django 3.2.5 on 2021-07-31 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_account_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='age',
            field=models.CharField(choices=[('16-20', '16-20'), ('20-24', '20-24'), ('24-30', '24-30'), ('30-40', '30-40'), ('40-50', '40-50'), ('50-60', '50-60'), ('60', '60+')], max_length=30),
        ),
    ]
