# Generated by Django 3.2.5 on 2021-08-08 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_account_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='age',
            field=models.CharField(choices=[('16-20', '16-20'), ('21-30', '21-30'), ('31-40', '31-40'), ('41-50', '41-50'), ('51-65', '51-65'), ('65+', '65+')], default='16-20', max_length=30),
        ),
    ]
