# Generated by Django 3.2.5 on 2021-09-11 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0010_alter_organisation_description'),
        ('account', '0010_alter_account_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='affiliated_with',
            field=models.ManyToManyField(null=True, related_name='affiliate_tag', to='organisations.Organisation'),
        ),
    ]
