# Generated by Django 3.2.5 on 2021-07-23 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.TextField(default='Type content here...', max_length=500),
        ),
    ]
