# Generated by Django 3.2.5 on 2021-07-28 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='field',
            field=models.CharField(default='Uncategorised', max_length=50, unique=True),
        ),
    ]
