# Generated by Django 3.2.5 on 2021-07-30 08:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0004_post_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ideas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True, unique=True)),
                ('field', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('estimated_cost', models.DecimalField(decimal_places=2, max_digits=6)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(default='Type content here...', max_length=500)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0)),
                ('is_user_led', models.BooleanField(default=True)),
                ('is_similar', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('image', models.ImageField(default='images/genger.png', upload_to='images/')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='idea_author', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
