# Generated by Django 3.2.5 on 2021-07-30 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_ideas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ideas',
            name='estimated_cost',
            field=models.DecimalField(decimal_places=2, default='£', max_digits=6),
        ),
    ]
