# Generated by Django 3.2.5 on 2021-07-30 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_ideas_estimated_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ideas',
            name='estimated_cost',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
