# Generated by Django 3.2.5 on 2021-07-30 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_ideas_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ideas',
            name='image',
            field=models.ImageField(default='images/genger.png', null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='ideas',
            name='is_approved',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='ideas',
            name='is_similar',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='ideas',
            name='notes',
            field=models.TextField(default='Type content here...', max_length=500, null=True),
        ),
    ]
