# Generated by Django 3.2.5 on 2021-07-30 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20210730_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ideas',
            name='field',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ideas',
            name='slug',
            field=models.SlugField(max_length=200, null=True, unique=True),
        ),
    ]
