# Generated by Django 3.2.5 on 2021-07-30 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20210730_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ideas',
            name='estimated_cost',
            field=models.DecimalField(decimal_places=2, default=300, max_digits=6),
        ),
        migrations.AlterField(
            model_name='ideas',
            name='field',
            field=models.CharField(default='Health', max_length=50, null=True),
        ),
    ]
