# Generated by Django 3.2.5 on 2021-08-01 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='ideas',
            name='is_related_to',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='blog.post'),
        ),
    ]
