# Generated by Django 3.2.5 on 2021-08-02 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_ideas'),
    ]

    operations = [
        migrations.AddField(
            model_name='ideas',
            name='is_related_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='idea_post', to='blog.post'),
        ),
    ]
