# Generated by Django 3.2.5 on 2021-08-02 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_ideas_is_related_to'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ideas',
        ),
    ]
