# Generated by Django 3.2.5 on 2021-08-02 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='image',
            field=models.ImageField(default='images/genger.png', null=True, upload_to='images/'),
        ),
    ]
