# Generated by Django 3.2.5 on 2021-08-04 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0031_alter_post_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='image',
            field=models.ImageField(default='images/gender.png', null=True, upload_to='images/'),
        ),
    ]
