# Generated by Django 3.2.5 on 2021-08-08 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0033_alter_comment_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.IntegerField(choices=[('Draft', 'Draft'), ('Publish', 'Publish')], default=0),
        ),
    ]
