# Generated by Django 3.2.5 on 2021-08-08 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0034_alter_post_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.IntegerField(choices=[('Draft', 'Draft'), ('Publish', 'Publish')], default='Draft'),
        ),
    ]
