# Generated by Django 3.2.5 on 2021-08-08 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0040_auto_20210806_0319'),
        ('blog', '0038_alter_post_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='severity',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='low', max_length=32),
        ),
    ]
