# Generated by Django 3.2.5 on 2021-08-08 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0040_auto_20210806_0319'),
        ('blog', '0039_auto_20210808_1723'),
    ]

    operations = [

    ]
