# Generated by Django 3.2.5 on 2021-08-08 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0040_alter_post_challenge'),
    ]

    operations = [
  
    ]
