# Generated by Django 3.2.5 on 2021-08-11 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0055_auto_20210811_0115'),
        ('blog', '0041_remove_post_challenge'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='challenge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_to_challenge', to='challenges.challenge'),
        ),
        migrations.AddField(
            model_name='post',
            name='endDate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='startDate',
            field=models.DateTimeField(null=True),
        ),
    ]
