# Generated by Django 3.2.5 on 2021-08-11 00:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('challenges', '0056_auto_20210811_0144'),
        ('blog', '0042_auto_20210811_0115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='field',
        ),
        migrations.AddField(
            model_name='post',
            name='department',
            field=models.ForeignKey(null=True, on_delete=models.SET('Dept not found'), related_name='dept', to='challenges.department'),
        ),
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.TextField(default='Type content here...', max_length=500),
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/challenges_images'),
        ),
        migrations.AddField(
            model_name='post',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='challenge_manager', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET('User not found'), related_name='challenge_winner', to=settings.AUTH_USER_MODEL),
        ),
    ]
