# Generated by Django 3.2.5 on 2021-08-11 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0045_auto_20210811_1806'),
    ]

    operations = [

    ]
