# Generated by Django 3.2.5 on 2021-08-12 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0048_alter_post_slug'),
    ]

    operations = [

    ]
