# Generated by Django 3.2.5 on 2021-08-12 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0065_alter_idea_slug'),
        ('blog', '0054_alter_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dept', to='challenges.department'),
        ),
    ]
