# Generated by Django 3.2.5 on 2021-08-13 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0056_alter_post_department'),
    ]

    operations = [

    ]
