# Generated by Django 3.2.5 on 2021-08-13 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0065_alter_idea_slug'),
        ('blog', '0059_alter_post_winner'),
    ]

    operations = [
    ]
