# Generated by Django 3.2.5 on 2021-08-13 01:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('challenges', '0065_alter_idea_slug'),
        ('blog', '0063_alter_post_winning_idea'),
    ]

    operations = [

    ]
