# Generated by Django 3.2.5 on 2021-08-13 01:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('challenges', '0065_alter_idea_slug'),
        ('blog', '0065_post_winning_idea'),
    ]

    operations = [
    
        migrations.AlterField(
            model_name='post',
            name='winner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='winner', to=settings.AUTH_USER_MODEL),
        ),
    ]
