# Generated by Django 3.2.5 on 2021-08-13 01:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion



class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0066_auto_20210813_0213'),
    ]

    operations = [

    ]