# Generated by Django 3.2.5 on 2021-08-13 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0065_alter_idea_slug'),
        ('blog', '0070_remove_post_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='winner', to='challenges.idea'),
        ),
    ]
