# Generated by Django 3.2.5 on 2021-08-14 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0070_alter_idea_department'),
        ('blog', '0071_post_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dept', to='challenges.department', unique=True),
        ),
    ]
