# Generated by Django 3.2.5 on 2021-08-27 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0004_organisation_image'),
        ('blog', '0073_alter_post_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='org_tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='postorgtag', to='organisations.organisation'),
        ),
    ]
