# Generated by Django 3.2.5 on 2021-09-19 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0107_alter_department_sub_department'),
        ('blog', '0082_alter_comment_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dept', to='challenges.department'),
        ),
    ]
