# Generated by Django 3.2.5 on 2021-08-26 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('challenges', '0078_alter_challenge_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('is_active', models.BooleanField(blank=True, max_length=50, null=True, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('specialty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='specialty', to='challenges.department')),
            ],
        ),
    ]
