# Generated by Django 3.2.5 on 2021-08-26 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='is_active',
            field=models.BooleanField(blank=True, max_length=50, null=True),
        ),
    ]
