# Generated by Django 3.2.5 on 2021-08-27 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0002_alter_organisation_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
