# Generated by Django 3.2.5 on 2021-08-27 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0078_auto_20210827_1404'),
        ('organisations', '0004_organisation_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='post1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='postorgtag1', to='blog.post'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='post2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='postorgtag2', to='blog.post'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='post3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='postorgtag3', to='blog.post'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='section1',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='organisation',
            name='section2',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='organisation',
            name='section3',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
