# Generated by Django 3.2.5 on 2021-08-28 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0006_auto_20210827_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='slug',
            field=models.SlugField(default='none', max_length=200, null=True),
        ),
    ]
