# Generated by Django 3.2.5 on 2021-09-02 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0007_organisation_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
