# Generated by Django 3.2.5 on 2021-09-02 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0079_auto_20210831_0159'),
        ('challenges', '0081_alter_challenge_description'),
        ('organisations', '0008_alter_organisation_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='post1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='postorgtag1', to='blog.post'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='post2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='postorgtag2', to='blog.post'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='post3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='postorgtag3', to='blog.post'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='specialty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='specialty', to='challenges.department'),
        ),
    ]
