# Generated by Django 3.2.5 on 2021-09-11 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0009_auto_20210902_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
