# Generated by Django 3.2.5 on 2021-09-12 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0012_alter_organisation_api_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='api_on',
            field=models.BooleanField(default=True, max_length=50),
        ),
    ]
