# Generated by Django 3.2.5 on 2021-09-15 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0013_alter_organisation_api_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='custom_form_on',
            field=models.BooleanField(default=True, max_length=50),
        ),
    ]
