# Generated by Django 3.2.5 on 2021-09-15 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0014_organisation_custom_form_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='custom_form_on',
            field=models.BooleanField(default=False, max_length=50),
        ),
        migrations.CreateModel(
            name='OrgForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('field_1', models.TextField(default='Type content here...', max_length=500)),
                ('field_2', models.TextField(default='Type content here...', max_length=500)),
                ('field_3', models.TextField(default='Type content here...', max_length=500)),
                ('field_4', models.TextField(default='Type content here...', max_length=500)),
                ('field_5', models.TextField(default='Type content here...', max_length=500)),
                ('field_6', models.TextField(default='Type content here...', max_length=500)),
                ('field_7', models.TextField(default='Type content here...', max_length=500)),
                ('field_8', models.TextField(default='Type content here...', max_length=500)),
                ('field_9', models.TextField(default='Type content here...', max_length=500)),
                ('field_10', models.TextField(default='Type content here...', max_length=500)),
                ('field_11', models.TextField(default='Type content here...', max_length=500)),
                ('field_12', models.TextField(default='Type content here...', max_length=500)),
                ('field_13', models.TextField(default='Type content here...', max_length=500)),
                ('field_14', models.TextField(default='Type content here...', max_length=500)),
                ('field_15', models.TextField(default='Type content here...', max_length=500)),
                ('field_16', models.TextField(default='Type content here...', max_length=500)),
                ('field_17', models.TextField(default='Type content here...', max_length=500)),
                ('organisation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='form_owner', to='organisations.organisation')),
            ],
        ),
    ]
