# Generated by Django 3.2.5 on 2021-09-15 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0018_auto_20210915_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgform',
            name='field_1',
            field=models.BooleanField(blank=True, default=False, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='orgform',
            name='field_2',
            field=models.BooleanField(blank=True, default=False, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='orgform',
            name='field_3',
            field=models.BooleanField(blank=True, default=False, max_length=50, null=True),
        ),
    ]
