# Generated by Django 3.2.5 on 2021-09-15 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0019_auto_20210915_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgform',
            name='field_10',
            field=models.BooleanField(blank=True, default=False, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='orgform',
            name='field_11',
            field=models.BooleanField(blank=True, default=False, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='orgform',
            name='field_12',
            field=models.BooleanField(blank=True, default=False, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='orgform',
            name='field_13',
            field=models.BooleanField(blank=True, default=False, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='orgform',
            name='field_14',
            field=models.BooleanField(blank=True, default=False, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='orgform',
            name='field_15',
            field=models.BooleanField(blank=True, default=False, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='orgform',
            name='field_16',
            field=models.BooleanField(blank=True, default=False, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='orgform',
            name='field_17',
            field=models.BooleanField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='orgform',
            name='field_4',
            field=models.BooleanField(blank=True, default=False, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='orgform',
            name='field_5',
            field=models.BooleanField(blank=True, default=False, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='orgform',
            name='field_6',
            field=models.BooleanField(blank=True, default=False, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='orgform',
            name='field_7',
            field=models.BooleanField(blank=True, default=False, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='orgform',
            name='field_8',
            field=models.BooleanField(blank=True, default=False, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='orgform',
            name='field_9',
            field=models.BooleanField(blank=True, default=False, max_length=50, null=True),
        ),
    ]
