# Generated by Django 3.2.5 on 2021-09-15 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0020_auto_20210915_1933'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrgForm',
        ),
    ]
