# Generated by Django 3.2.5 on 2021-10-04 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0023_auto_20210920_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='about',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='section1',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='section2',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='section3',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
