# Generated by Django 3.2.5 on 2021-07-25 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0002_auto_20210725_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ideas',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ideas',
            name='is_similar',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ideas',
            name='is_user_led',
            field=models.BooleanField(default=True),
        ),
    ]
