# Generated by Django 3.2.5 on 2021-07-30 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0004_auto_20210729_2123'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ideas',
        ),
    ]
