# Generated by Django 3.2.5 on 2021-08-02 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0010_alter_ideas_is_related_to'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ideas',
        ),
    ]
