# Generated by Django 3.2.5 on 2021-08-02 00:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0023_delete_ideas'),
        ('challenges', '0012_ideas'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Challenges',
            new_name='Challenge',
        ),
        migrations.RenameModel(
            old_name='Ideas',
            new_name='Idea',
        ),
    ]
