# Generated by Django 3.2.5 on 2021-08-02 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0013_auto_20210802_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='field',
            field=models.CharField(choices=[('Health', 'Health'), ('Culture', 'Culture'), ('Job Satisfaction', 'Job Satisfaction'), ('Relationships', 'Relationships'), ('Leadership', 'Leadership'), ('Data', 'Data')], default='low', max_length=32),
        ),
        migrations.AlterField(
            model_name='idea',
            name='image',
            field=models.ImageField(default='images/gender.png', null=True, upload_to='images/'),
        ),
    ]
