# Generated by Django 3.2.5 on 2021-08-03 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0014_auto_20210802_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='image',
            field=models.ImageField(default='images/gender.png', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='severity',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='low', max_length=32),
        ),
    ]
