# Generated by Django 3.2.5 on 2021-08-04 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0016_auto_20210803_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='field',
            field=models.CharField(choices=[('Health', 'Health'), ('Culture', 'Culture'), ('Job Satisfaction', 'Job Satisfaction'), ('Relationships', 'Relationships'), ('Leadership', 'Leadership'), ('Data', 'Data'), ('Other', 'Other')], default='low', max_length=32),
        ),
    ]
