# Generated by Django 3.2.5 on 2021-08-04 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0017_alter_idea_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='field',
            field=models.CharField(choices=[('Health', 'Health'), ('Culture', 'Culture'), ('Job Satisfaction', 'Job Satisfaction'), ('Relationships', 'Relationships'), ('Leadership', 'Leadership'), ('Data', 'Data'), ('Other', 'Other')], max_length=50),
        ),
    ]
