# Generated by Django 3.2.5 on 2021-08-04 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0019_auto_20210804_1546'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='field',
            new_name='department',
        ),
        migrations.AddField(
            model_name='department',
            name='sub_department',
            field=models.CharField(choices=[('Health', 'Health'), ('Culture', 'Culture'), ('Job Satisfaction', 'Job Satisfaction'), ('Relationships', 'Relationships'), ('Leadership', 'Leadership'), ('Data', 'Data'), ('Other', 'Other')], default='low', max_length=32),
        ),
    ]
