# Generated by Django 3.2.5 on 2021-08-04 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0020_auto_20210804_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='field',
            field=models.CharField(default='None', max_length=200),
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
