# Generated by Django 3.2.5 on 2021-08-04 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0022_auto_20210804_1558'),
    ]

    
