# Generated by Django 3.2.5 on 2021-08-04 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0025_auto_20210804_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='department',
            field=models.ForeignKey(null=True, on_delete=models.SET('Dept not found'), related_name='idea_department', to='challenges.department'),
        ),
    ]
