# Generated by Django 3.2.5 on 2021-08-04 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0026_idea_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='department',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='department',
            name='sub_department',
            field=models.CharField(default='None', max_length=50),
        ),
    ]
