# Generated by Django 3.2.5 on 2021-08-04 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0027_auto_20210804_1648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='field',
        ),
        migrations.RemoveField(
            model_name='idea',
            name='field',
        ),
        migrations.AddField(
            model_name='department',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
