# Generated by Django 3.2.5 on 2021-08-04 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0029_alter_department_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='is_core',
            field=models.BooleanField(default=False),
        ),
    ]
