# Generated by Django 3.2.5 on 2021-08-04 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0030_department_is_core'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='department',
            field=models.CharField(choices=[('Health', 'Health'), ('Culture', 'Culture'), ('Job Satisfaction', 'Job Satisfaction'), ('Relationships', 'Relationships'), ('Leadership', 'Leadership'), ('Data', 'Data'), ('Other', 'Other')], default='Other', max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='sub_department',
            field=models.CharField(default='None', max_length=50, unique=True),
        ),
    ]
