# Generated by Django 3.2.5 on 2021-08-04 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0032_alter_comment_image'),
        ('challenges', '0032_alter_department_sub_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='idea_challenge', to='blog.post'),
        ),
        migrations.AlterField(
            model_name='department',
            name='department',
            field=models.CharField(choices=[('Health', 'Health'), ('Culture', 'Culture'), ('Job Satisfaction', 'Job Satisfaction'), ('Relationships', 'Relationships'), ('Leadership', 'Leadership'), ('Data', 'Data'), ('Other', 'Other')], default='Other', max_length=32),
        ),
        migrations.AlterField(
            model_name='department',
            name='sub_department',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
