# Generated by Django 3.2.5 on 2021-08-04 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0032_alter_comment_image'),
        ('challenges', '0034_remove_idea_is_related_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ideas', to='blog.post'),
        ),
    ]
