# Generated by Django 3.2.5 on 2021-08-04 21:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('challenges', '0035_alter_idea_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='likes',
            field=models.ManyToManyField(related_name='idea_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
