# Generated by Django 3.2.5 on 2021-08-05 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0036_idea_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='sub_department',
            field=models.ForeignKey(null=True, on_delete=models.SET('Dept not found'), related_name='idea_sub_department', to='challenges.department'),
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('department', 'sub_department')},
        ),
    ]
