# Generated by Django 3.2.5 on 2021-08-05 21:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('challenges', '0037_auto_20210805_1434'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdeaComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('comment', models.TextField(default='Type content here...', max_length=500)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(default='images/gender.png', null=True, upload_to='images/')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='idea_comment_author', to=settings.AUTH_USER_MODEL)),
                ('idea', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='idea_comments', to='challenges.idea')),
                ('likes', models.ManyToManyField(related_name='idea_comment_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
