# Generated by Django 3.2.5 on 2021-08-05 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0038_ideacomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ideacomment',
            name='idea',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='challenges.idea'),
        ),
    ]
