# Generated by Django 3.2.5 on 2021-08-06 02:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('challenges', '0039_alter_ideacomment_idea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET('User not found'), related_name='challenge_winner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ideacomment',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='idea_comment_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
