# Generated by Django 3.2.5 on 2021-08-09 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0040_auto_20210806_0319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='image',
            field=models.ImageField(default='images/sitemap.png', null=True, upload_to='images/'),
        ),
    ]
