# Generated by Django 3.2.5 on 2021-08-09 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0042_alter_idea_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='image',
            field=models.ImageField(blank=True, default='media/images/sitemap.png', null=True, upload_to='media/images/'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='notes',
            field=models.TextField(blank=True, default='Type content here...', max_length=500, null=True),
        ),
    ]
