# Generated by Django 3.2.5 on 2021-08-11 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0054_alter_challenge_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='endDate',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='startDate',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='status',
        ),
        migrations.AlterField(
            model_name='challenge',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/challenges_images'),
        ),
    ]
