# Generated by Django 3.2.5 on 2021-08-11 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0055_auto_20210811_0115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='winner',
        ),
        migrations.AlterField(
            model_name='challenge',
            name='department',
            field=models.ForeignKey(null=True, on_delete=models.SET('Dept not found'), related_name='category', to='challenges.department'),
        ),
    ]
