# Generated by Django 3.2.5 on 2021-08-12 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0056_auto_20210811_0144'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='stage',
            field=models.CharField(blank=True, choices=[('accepted', 'Accepted'), ('rejected', 'Rejected'), ('in development', 'In Development'), ('complete', 'Complete')], max_length=32, null=True),
        ),
    ]
