# Generated by Django 3.2.5 on 2021-08-12 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0057_idea_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='slug',
            field=models.SlugField(max_length=2000, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='idea',
            name='stage',
            field=models.CharField(blank=True, choices=[('accepted', 'Accepted'), ('rejected', 'Rejected'), ('in development', 'In Development'), ('complete', 'Complete')], max_length=2000, null=True),
        ),
    ]
