# Generated by Django 3.2.5 on 2021-08-12 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0058_auto_20210812_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='slug',
            field=models.SlugField(default=5, max_length=2000),
            preserve_default=False,
        ),
    ]
