# Generated by Django 3.2.5 on 2021-08-12 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0059_alter_idea_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idea',
            name='stage',
        ),
    ]
