# Generated by Django 3.2.5 on 2021-08-12 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0060_remove_idea_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='slug',
            field=models.SlugField(max_length=200, null=True, default='none'),
        ),
    ]
