# Generated by Django 3.2.5 on 2021-08-12 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0061_alter_idea_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='slug',
            field=models.SlugField(default='none', max_length=200, null=True),
        ),
    ]
