# Generated by Django 3.2.5 on 2021-08-12 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0062_alter_idea_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='stage',
            field=models.CharField(blank=True, choices=[('accepted', 'Accepted'), ('rejected', 'Rejected'), ('in development', 'In development'), ('complete', 'Complete')], max_length=2000, null=True),
        ),
    ]
