# Generated by Django 3.2.5 on 2021-08-13 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0065_alter_idea_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='idea_department', to='challenges.department'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='sub_department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='idea_sub_department', to='challenges.department'),
        ),
    ]
