# Generated by Django 3.2.5 on 2021-08-13 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0066_auto_20210813_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='idea_department', to='challenges.department'),
        ),
    ]
