# Generated by Django 3.2.5 on 2021-08-14 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0068_alter_idea_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='idea_department', to='challenges.department'),
        ),
    ]
