# Generated by Django 3.2.5 on 2021-08-14 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0073_alter_post_department'),
        ('challenges', '0073_alter_idea_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='idea_department', to='blog.post'),
        ),
    ]
