# Generated by Django 3.2.5 on 2021-08-14 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0075_alter_idea_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='sub_department',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together=set(),
        ),
    ]
