# Generated by Django 3.2.5 on 2021-08-26 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0077_auto_20210814_0119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category', to='challenges.department'),
        ),
    ]
