# Generated by Django 3.2.5 on 2021-08-30 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0079_auto_20210827_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='description',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='idea',
            name='estimated_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=300, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='idea',
            name='notes',
            field=models.TextField(blank=True, default='', max_length=500, null=True),
        ),
    ]
