# Generated by Django 3.2.5 on 2021-08-31 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0080_auto_20210830_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='description',
            field=models.TextField(default='', max_length=500),
        ),
    ]
