# Generated by Django 3.2.5 on 2021-09-02 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0082_alter_idea_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='sub_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='idea_sub_department', to='challenges.department'),
        ),
    ]
