# Generated by Django 3.2.5 on 2021-09-03 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0009_auto_20210902_1403'),
        ('challenges', '0083_alter_idea_sub_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idea',
            name='org_tag',
        ),
        migrations.AddField(
            model_name='idea',
            name='org_tag',
            field=models.ManyToManyField(null=True, related_name='ideaorgtag', to='organisations.Organisation'),
        ),
    ]
