# Generated by Django 3.2.5 on 2021-09-11 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0086_alter_ideacomment_idea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
