# Generated by Django 3.2.5 on 2021-09-13 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0087_alter_challenge_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ideacomment',
            name='comment',
            field=models.CharField(max_length=500),
        ),
    ]
