# Generated by Django 3.2.5 on 2021-09-13 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0088_alter_ideacomment_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ideacomment',
            name='comment',
            field=models.TextField(max_length=500),
        ),
    ]
