# Generated by Django 3.2.5 on 2021-09-13 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0089_alter_ideacomment_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ideacomment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
