# Generated by Django 3.2.5 on 2021-09-15 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0090_alter_ideacomment_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='description',
            field=models.TextField(default='', error_messages={'unique': 'This challenge is too similar to an existing one'}, max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='title',
            field=models.CharField(error_messages={'unique': 'A challenge with this title already exists'}, max_length=200, unique=True),
        ),
    ]
