# Generated by Django 3.2.5 on 2021-09-15 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0093_auto_20210915_0959'),
    ]

    operations = [

    ]