# Generated by Django 3.2.5 on 2021-09-15 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0094_auto_20210915_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='idea_department', to='challenges.department'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='sub_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='idea_sub_department', to='challenges.department'),
        ),
    ]
