# Generated by Django 3.2.5 on 2021-09-15 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0097_alter_idea_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='department',
            field=models.CharField(choices=[('Health', 'Health'), ('Culture', 'Culture'), ('Job Satisfaction', 'Job Satisfaction'), ('Relationships', 'Relationships'), ('Leadership', 'Leadership'), ('Data', 'Data'), ('Other', 'Other')], default='Other', max_length=32, unique=True),
        ),
    ]
