# Generated by Django 3.2.5 on 2021-09-16 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0099_orgform'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orgform',
            old_name='field_1',
            new_name='NICE_Tier1_DTAC_evidence_in_place',
        ),
        migrations.RenameField(
            model_name='orgform',
            old_name='field_10',
            new_name='NICE_Tier2_DTAC_evidence_in_place',
        ),
        migrations.RenameField(
            model_name='orgform',
            old_name='field_11',
            new_name='ce_mark_dcb_register',
        ),
        migrations.RenameField(
            model_name='orgform',
            old_name='field_12',
            new_name='cost_of_dev_and_support_agreed',
        ),
        migrations.RenameField(
            model_name='orgform',
            old_name='field_13',
            new_name='data_and_model_agreed',
        ),
        migrations.RenameField(
            model_name='orgform',
            old_name='field_14',
            new_name='ig_agreements_in_place',
        ),
        migrations.RenameField(
            model_name='orgform',
            old_name='field_15',
            new_name='in_sandbox',
        ),
        migrations.RenameField(
            model_name='orgform',
            old_name='field_2',
            new_name='ip_agreement_in_place',
        ),
        migrations.RenameField(
            model_name='orgform',
            old_name='field_3',
            new_name='is_open_source_partnership',
        ),
        migrations.RenameField(
            model_name='orgform',
            old_name='field_4',
            new_name='is_released_and_supported',
        ),
        migrations.RenameField(
            model_name='orgform',
            old_name='field_5',
            new_name='iso_supplier',
        ),
        migrations.RenameField(
            model_name='orgform',
            old_name='field_6',
            new_name='risk_and_mitigations_are_public',
        ),
        migrations.RenameField(
            model_name='orgform',
            old_name='field_7',
            new_name='safety_officer_stated',
        ),
        migrations.RenameField(
            model_name='orgform',
            old_name='field_8',
            new_name='user_kpis_is_an_ai_pathway_are_defined',
        ),
        migrations.RenameField(
            model_name='orgform',
            old_name='field_9',
            new_name='user_to_board_approval_obtained',
        ),
    ]
