# Generated by Django 3.2.5 on 2021-09-16 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0100_auto_20210916_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgform',
            name='description',
            field=models.TextField(blank=True, error_messages={'unique': 'Idea description is too similar to an existing one'}, max_length=500, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='orgform',
            name='title',
            field=models.CharField(blank=True, default=' ', error_messages={'unique': 'Idea title is too similar to an existing one'}, max_length=200, null=True, unique=True),
        ),
    ]
