# Generated by Django 3.2.5 on 2021-09-16 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0101_auto_20210916_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgform',
            name='NICE_Tier1_DTAC_evidence_in_place',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='orgform',
            name='NICE_Tier2_DTAC_evidence_in_place',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='orgform',
            name='ce_mark_dcb_register',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='orgform',
            name='cost_of_dev_and_support_agreed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='orgform',
            name='data_and_model_agreed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='orgform',
            name='field_16',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='orgform',
            name='field_17',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='orgform',
            name='ig_agreements_in_place',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='orgform',
            name='ip_agreement_in_place',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='orgform',
            name='is_open_source_partnership',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='orgform',
            name='is_released_and_supported',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='orgform',
            name='iso_supplier',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='orgform',
            name='risk_and_mitigations_are_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='orgform',
            name='safety_officer_stated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='orgform',
            name='user_kpis_is_an_ai_pathway_are_defined',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='orgform',
            name='user_to_board_approval_obtained',
            field=models.BooleanField(default=False),
        ),
    ]
