# Generated by Django 3.2.5 on 2021-09-18 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0104_alter_department_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='is_pridar',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
