# Generated by Django 3.2.5 on 2021-09-19 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0105_idea_is_pridar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='is_pridar',
            field=models.BooleanField(default=False),
        ),
    ]
