# Generated by Django 3.2.5 on 2021-09-19 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0106_alter_idea_is_pridar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='sub_department',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
