# Generated by Django 3.2.5 on 2021-10-01 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0110_alter_challenge_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/challenge_images_lib'),
        ),
    ]
